### ISSUE TITLE
Generate JavaScript fails

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/freebase_searchwidget_polymer#2]
../../../../my/dart/freebase_searchwidget/web/packages/path/path.dart:49:23: Hint: Can't find 'dart.io.Directory.current' in the current library.
Did you forget to add an import?
@MirrorsUsed(targets: 'dart.dom.html.window, '
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../my/dart/freebase_searchwidget/web/packages/path/path.dart:49:23: Hint: Can't find 'dart.io.Platform.operatingSystem' in the current library.
Did you forget to add an import?
@MirrorsUsed(targets: 'dart.dom.html.window, '
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../my/dart/freebase_searchwidget/web/packages/freebase_searchwidget/components/freebase_searchwidget.dart:243:7: expected a string
      Status.START: '',
      ^^^^^^^^^^^^
Error: Compilation failed.

**Comment by alizdavoodi** [comment]
+1

**Comment by zoechi** [comment]
Hi David,

did you try freebase_searchwidget or did you just find the error message in Google?
Did you use the published package or the source from the repository?

I'm currently working to port polymer-elements from JS to Dart and there I also have problems building to JS with imported elements. There are still limitations in Polymer.dart so I didn't work much this problem on freebase_searchwidget either. 

I just tried to built my simple demo page for freebase_searchwidget and I still get warnings (like them above) but the build didn't fail.

Would you mind providing some additional information about your use case?

Günter
